### ISSUE TITLE
IKFast Plugin Tutorial errors

### ISSUE THREAD

**Issue by 0ldham** [ros-planning/moveit_tutorials#103]
While following the instructions in the [IKFast Plugin](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/ikfast_tutorial.html) tutorial and trying to convert the PR2 URDF file found in pr2_common to Collada format, I receive the errors: 

`[ERROR] [1502306846.769705032]: No link elements found in urdf file
[ERROR] [1502306846.769832718]: failed to open urdf file pr2.urdf.xacro
`

Not really sure what's causing this problem.

**Comment by felixvd** [comment]
Something might have been wrong with how you specify the file's location. That section of the tutorial has changed considerably since this post, so I'll close this.
