### ISSUE TITLE
Remove all links to old Wiki

### ISSUE THREAD

**Issue by davetcoleman** [ros-planning/moveit_tutorials#129]
MoveIt! used to use a Wiki and these tutorials still linked to it, so I re-hosted it on my personal website temporarily (picknik.io). The conversion to 100% tutorials is still complete, but we need someone to remove the final picknik.io links and at the same time copy the relevant content into the tutorials. After that I will take down that wiki once and for all.

**Comment by BryceStevenWilley** [comment]
Should be resolved with https://github.com/ros-planning/moveit_tutorials/pull/136.
