### ISSUE TITLE
update on Setup Assistant Tutorial

### ISSUE THREAD

**Issue by Uroko** [ros-planning/moveit_tutorials#130]
I found a fix to the Setup Assistant Tutorial.
When I followed it and tried the next MoveIt! RViz Plugin Tutorial,
the interactive marker didn't show up, and there were errors saying
the arm is not a chain, sothe solver cannot work.

From googling I found the workaround here,
https://groups.google.com/forum/#!topic/moveit-users/Sou7saUo6mY
I had to unselect 2 joints in the arm group, 
"r_forearm_cam_frame_joint" and "r_forearm_cam_optical_frame_joint".  

The resulting 9 joint set is same as described in tutorial,
I suppose the cam joints were added afterward.
So the sentence should be updated like 
`Click on r_shoulder_pan_joint, hold down the Shift button on your keyboard and then click on the r_wrist_roll_joint.`
to 
`Click on r_shoulder_pan_joint, hold down the Ctrl button on your keyboard and then click each joint down to the r_wrist_roll_joint, except for two joints named "r_forearm_cam*".`

that would be like this:
![image](https://user-images.githubusercontent.com/32997074/31860234-2a291e28-b752-11e7-8488-306608c43d4b.png)

Please check out.
Uroko

**Comment by felixvd** [comment]
Thanks for the report. Considering that the tutorial uses the panda now, I'll close this.
