### ISSUE TITLE
collision contact tutorial seems to be broken

### ISSUE THREAD

**Issue by mlautman** [ros-planning/moveit_tutorials#153]
I'm running ROS Kinetic on Ubuntu 16.04 and it seems that the launch file for the collision contact tutorial seems to be broken. 

Rviz comes up without a robot state or MotionPlanning display. 
![collision_contact_rviz](https://user-images.githubusercontent.com/3253549/36401262-8b2edbf0-1593-11e8-9bf1-08774c3f1be1.png)

I  am running roslaunch moveit_tutorials collision_contact_tutorial.launch and both the pr2_moveit_config and moveit_tutorials are in my ROS_PACKAGE_PATH

**Comment by BryceStevenWilley** [comment]
I believe this is intentional: [the tutorial](https://github.com/ros-planning/moveit_tutorials/blob/kinetic-devel/doc/collision_contact_tutorial.rst#rviz-setup) states that 'you will have to add some displays to see the objects your code is publishing.'

> When Rviz starts up you will have to add some displays to see the objects your code is publishing. This is done in the "Displays" panel in rviz.
>
>    * Under GlobalOptions set FixedFrame to /base_footprint.
>    * Cick Add and (under moveit_ros_visualization) add a RobotState display.
>        * Set the RobotState::RobotDescription to robot_description
>        * Set the RobotState::RobotStateTopic to interactive_robot_state
>        * Set the RobotState::RobotAlpha to 0.3 (to make the robot transparent and see the collision points)
>   * Click Add and (under Rviz) add a Marker display.
 >       * Set the Marker::MarkerTopic to interactive_robot_markers
>    * Click Add and (under Rviz) add a InteractiveMarkers display.
 >       * Set the Marker::UpdateTopic to interactive_robot_imarkers/update
>    * Click Add and (under Rviz) add a MarkerArray display.
>        * Set the Marker::UpdateTopic to interactive_robot_marray.
>
> You should now see the PR2 robot with 2 interactive markers which you can drag around.

**Comment by mlautman** [comment]
Thanks
