### ISSUE TITLE
catkin make hang on 92% on turtle bot 3 burger

### ISSUE THREAD

**Issue by golkhatab** [ros-planning/moveit_tutorials#162]
when run catkin make  on turtle bot 3 burger robots  catkin make stops and hangs , it  arrive  to
 "Building CXX object turtlebot3/turtlebot3_bringup/CMakeFiles/turtlebot3_diagnostics.dir/src/turtlebot3_diagnostics.cpp.o "

**Comment by v4hn** [comment]
has nothing to do with this.
