### ISSUE TITLE
incorrect link in installation page

### ISSUE THREAD

**Issue by jash101** [ros-planning/moveit_tutorials#174]
The link ( http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/ros_visualization/visualization_tutorial.html ) on the installation page under quickstart section is incorrect. Please correct it.

**Comment by mlautman** [comment]
Hey @jash101 We appreciate the feedback but I don't see a broken link. Is this still broken? The buildfarm runs every few days.

If the link is still broken, please post a link with more exact instructions to find the hypertext on the tutorial page. 

Also, in addition to opening an issue I would encourage you to open a PR in the future. I can mentor you in how to do this if you run into blockers :)

**Comment by davetcoleman** [comment]
@jash101 is referring to the bottom of:
http://moveit.ros.org/install/

Thanks for catching this! Do you mind making a PR to fix it? See:
https://github.com/ros-planning/moveit.ros.org/blob/gh-pages/install/index.markdown

**Comment by jash101** [comment]
@davetcoleman sure I'll do that

**Comment by jash101** [comment]
@davetcoleman I think it's already been fixed. Sorry for the late reply

**Comment by davetcoleman** [comment]
Great. In the future be sure to close an issue if you think its resolved :)
