### ISSUE TITLE
Improvements and generalisation of bag_publisher_maintain_time.cpp

### ISSUE THREAD

**Issue by Ridhwanluthra** [ros-planning/moveit_tutorials#193]
The [bag publisher with time maintainence](https://github.com/ros-planning/moveit_tutorials/pull/178/commits/bb6a59fc0968e593de52737e5642c35a07ceb22c#diff-0684d7b977bfb95322e222e5c1fd3316) is being added as a part of the [perception_pipeline_tutorial](https://github.com/ros-planning/moveit_tutorials/pull/178).

This is node is used to read a topic from a bag and publish it on a loop while using the current ROS time. It is being added to use rosbags in tutorials which contain as less as a single message. This will enable us to add any bags corresponding to any tutorial right in git.

I would like to improve the working of this and generalise it to be usable by other tutorials as a utility.

**Comment by mlautman** [comment]
That would be great!
