### ISSUE TITLE
Can't see the trajectory line of the manipulator

### ISSUE THREAD

**Issue by moucrob** [ros-planning/moveit_tutorials#197]
Hello,
I see in move_group_interface_tutorial.cpp that, line 137, the author uses : 
`visual_tools.publishTrajectoryLine(my_plan.trajectory_, joint_model_group);`.
However when I go to [http://docs.ros.org/kinetic/api/rviz_visual_tools/html/classrviz__visual__tools_1_1RvizVisualTools.html](url), it seems that only methods uptodate existing are publishAxisPath, publishLine, publishPath, but not anymore that publishTrajectoryLine, which seems to be once used during indigo and PR2 era.

Am I wrong? (I'm a beginner)
Actually I would want to use this tutorial snippet to write my own sequence, but my current problem is that I cannot (though would want to) see my joint frames moving while I use the trajectory slider. They only appear in the initial fixed pose of the robot because I hardcoded them in moveit.rviz / saved the rviz conf...

**Comment by mlautman** [comment]
This type of question should be posted to [ROS answers](https://answers.ros.org/questions/) not as an issue on github. You will get a more in depth answer quicker over there.

If you look at the source code for that tutorial, you will see that visual_tools is a [MoveItVisualTools](https://github.com/ros-planning/moveit_visual_tools) object not a RvizVisualTools object.
