### ISSUE TITLE
pick_place_tutotrial and pick_place_tutorial

### ISSUE THREAD

**Issue by itfanr** [ros-planning/moveit_tutorials#198]
http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/pick_place/pick_place_tutorial.html

The rst source file is correct but the html is not.

**Comment by felixvd** [comment]
#196

**Comment by itfanr** [comment]
@felixvd Thank you.

**Comment by mlautman** [comment]
The buildfarm for the website runs every few days
