### ISSUE TITLE
travis rake error

### ISSUE THREAD

**Issue by v4hn** [ros-planning/moveit_tutorials#20]
Travis fails for this repo with some unrelated `rake` error.

See e.g. #19 :

> 0.09s$ rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
The command "rake" exited with 1.
Done. Your build exited with 1.

**Comment by davetcoleman** [comment]
I just turned on travis for this repo, but it has no config until https://github.com/ros-planning/moveit_tutorials/pull/17 is merged in. The error you are seeing is the default Travis error and should be ignored.
