### ISSUE TITLE
move_group_interface_tutorials -Failed to fetch current robot state

### ISSUE THREAD

**Issue by Joneny** [ros-planning/moveit_tutorials#222]
**Description**
  I have used kinova jabo arm in Ubuntu14.04 and  download the ros package of jaco form [https://github.com/Kinovarobotics/kinova-ros](url).All things work well!when I move the code to Ubuntu16.04,something wrong!
  When i run roslaunch j2n6s300_moveit_config j2n6s300_demo.launch 
  The error occur:
[ERROR] [1536291737.426281012]: SpinnerMonitor: single-threaded spinner after multi-threaded one(s).Attempt to spin a callback queue from two spinners, one of them being single-threaded.
In the future this will throw an exception! Only allowed for backwards compatibility.
  but i can also do some work,should i ignore this error?

  When i run the code form move_group_interface_tutorial,which is just the code of move to a pose goal like this:
 ros::init(argc, argv, "move_group_interface_tutorial");
  ros::NodeHandle node_handle;
  ros::AsyncSpinner spinner(5);
  spinner.start();
  // of the group you would like to control and plan for.
  moveit::planning_interface::MoveGroupInterface group("arm");

  // We will use the :planning_scene_interface:`PlanningSceneInterface`
  // class to deal directly with the world.
  moveit::planning_interface::PlanningSceneInterface planning_scene_interface;

  const robot_state::JointModelGroup* joint_model_group = group.getCurrentState()->getJointModelGroup("arm");
  namespace rvt = rviz_visual_tools;
  moveit_visual_tools::MoveItVisualTools visual_tools("base_link");
  visual_tools.deleteAllMarkers();

  visual_tools.loadRemoteControl();

  Eigen::Affine3d text_pose = Eigen::Affine3d::Identity();
  text_pose.translation().z() = 1.75;
  visual_tools.publishText(text_pose, "MoveGroupInterface Demo",rvt::WHITE, rvt::XLARGE);

  visual_tools.trigger();

  ROS_INFO_NAMED("tutorial", "Reference frame %s", group.getPlanningFrame().c_str());

  visual_tools.prompt("Press 'next' in the RcizVisualToolsGui window to start the demo");

  geometry_msgs::Pose target_pose1;
  target_pose1.orientation.w = 1.0;
  target_pose1.position.x = 0.28;
  target_pose1.position.y = -0.2;
  target_pose1.position.z = 0.5;
  group.setPoseTarget(target_pose1);

  moveit::planning_interface::MoveGroupInterface::Plan my_plan;

  bool success = (group.plan(my_plan) == moveit::planning_interface::MoveItErrorCode::SUCCESS);
  ROS_INFO_NAMED("tutorial", "Visualizing plan 1 (pose goal) %s", success?"" : "FAILED");

  //visualizing plans

  ROS_INFO_NAMED("tutorial", "Visualizing plan 1 as trajectory line");
  visual_tools.publishAxisLabeled(target_pose1, "pose1");
  visual_tools.publishText(text_pose, "Pose Goal", rvt::WHITE, rvt::XLARGE);
  visual_tools.publishTrajectoryLine(my_plan.trajectory_,joint_model_group);
  visual_tools.trigger();
  visual_tools.prompt("Press 'next' in the RvizVisualToolsGui window to continue the demo");

  group.move();
}
  Error appears like ：
[ INFO] [1536291765.545386969]: Didn't received robot state (joint angles) with recent timestamp within 1 seconds.
Check clock synchronization if your are running ROS across multiple machines!
[ERROR] [1536291765.545484558]: Failed to fetch current robot state
Segmentation fault (core dumped)

what should i do ? im so appreciate about your answer!

Environment:
ros kinetic
Ubuntu 16.04

**Comment by DangMinh24** [comment]
Hi @Joneny, have you found the solution yet? I have the same problem.
