### ISSUE TITLE
Problem in "Move Group Python Interface"

### ISSUE THREAD

**Issue by fstern97** [ros-planning/moveit_tutorials#229]
I did the tutorials on the MoveIt! website, but I got stuck at "Move Group Python Interface". After executing "roslaunch panda_moveit_config demo.launch" and "rosrun moveit_tutorials move_group_python_interface_tutorial.py" the robotic arm is supposed to plan and move its arm according to the tutorial. I can see in the RViz Interface that the path is planned but never executed. Instead the error message 

ABORTED: Solution found but controller failed during execution

is shown.

**Comment by mlautman** [comment]
Please give us more information about your setup. Closing until we are able to get more information
