### ISSUE TITLE
IKfast for a dual-arm robot

### ISSUE THREAD

**Issue by Chunting** [ros-planning/moveit_tutorials#275]
HI, all,
I have a problem to generate ikfast plugin for my dual-arm-robot.
The working environment is Ubuntu 14.04, and ROS version is of course indigo.
My question is how to select the baselink and eelink? Since I have a robot frame (stand1 and stand2 ) in my project

![dual_arm_robot](https://user-images.githubusercontent.com/3312409/50732468-01e54200-11b7-11e9-8a4e-a05529aa6297.png)

This is my links info:
================================================
```
name                 index parents             
-----------------------------------------------
world                0                         
table                1     world               
stand1               2     world               
stand2               3     stand1              
left_base_link       4     stand2              
left_base            5     left_base_link      
left_shoulder_link   6     left_base_link      
left_upper_arm_link  7     left_shoulder_link  
left_forearm_link    8     left_upper_arm_link 
left_wrist_1_link    9     left_forearm_link   
left_wrist_2_link    10    left_wrist_1_link   
left_wrist_3_link    11    left_wrist_2_link   
left_ee_link         12    left_wrist_3_link   
right_base_link      13    stand2              
right_base           14    right_base_link     
right_shoulder_link  15    right_base_link     
right_upper_arm_link 16    right_shoulder_link 
right_forearm_link   17    right_upper_arm_link
right_wrist_1_link   18    right_forearm_link  
right_wrist_2_link   19    right_wrist_1_link  
right_wrist_3_link   20    right_wrist_2_link  
right_ee_link        21    right_wrist_3_link  
```
==============================================================

To generate ikfast plugin for the left arm, the command is: 

`python `openrave-config --python-dir`/openravepy/_openravepy_/ikfast.py --robot=dual_arm_robot.dae --iktype=transform6d --baselink=0 --eelink=12 --savefile="/ikfast61_left_manipulator.cpp"`

But how should I generate the plugin for the right arm? Since I installed these two arms on  a robot frame. Thus how should I indicate the baselink and eelink?

`python `openrave-config --python-dir`/openravepy/_openravepy_/ikfast.py --robot=dual_arm_robot.dae --iktype=transform6d --baselink=13 --eelink=21 --savefile="/ikfast61_left_manipulator.cpp"`

Alternatively, can I set the baselink as stand2? If so, will the plugin work correctly?

`python `openrave-config --python-dir`/openravepy/_openravepy_/ikfast.py --robot=dual_arm_robot.dae --iktype=transform6d --baselink=3 --eelink=12 --savefile="/ikfast61_left_manipulator.cpp"

python `openrave-config --python-dir`/openravepy/_openravepy_/ikfast.py --robot=dual_arm_robot.dae --iktype=transform6d --baselink=13 --eelink=21 --savefile="/ikfast61_right_manipulator.cpp"
`

Thanks,
Chunting

**Comment by mlautman** [comment]
This is not an issue with the tutorials so I am closing it. This should be asked on [ROS Answers](https://answers.ros.org/questions/)

**Comment by mlautman** [comment]
> Alternatively, can I set the baselink as stand2? If so, will the plugin work correctly?

Questions like this can be answered by a quick test. 

That said, you should only need one IKFast analytic solution per robot arm since the geometry is identical. You can always generate two kinematic solver packages from the same solution if you want.  Furthermore, in the case of the UR you ROS-I provides an analytic solution for the UR's in the [universal_robot](https://github.com/ros-industrial/universal_robot) repo. (Note: I am not 100% certain that the analytic solution in the ROS-I repo will work with the E-Series).
