### ISSUE TITLE
docs.ros.org not building melodic tutorials

### ISSUE THREAD

**Issue by mlautman** [ros-planning/moveit_tutorials#293]
The melodic tutorials at http://docs.ros.org/melodic/api/moveit_tutorials/html/ don't seem to be getting built anymore. 
@130s can you look into this?

**Comment by 130s** [comment]
https://github.com/ros/rosdistro/pull/20419 should fix once merged. @mlautman Could you check if the branch in that PR correct for Melodic?

**Comment by davetcoleman** [comment]
Link is still broken, sometimes it takes a few days

**Comment by davetcoleman** [comment]
Link works! @mlautman can you update the README.md of this repo to point to http://docs.ros.org/melodic/api/moveit_tutorials/html/ ?

And can you update the version info at the top of the tutorial pages? Thanks!
