### ISSUE TITLE
Workspace for Testing MoveIt

### ISSUE THREAD

**Issue by rmerriam** [ros-planning/moveit_tutorials#311]
I’ve been very frustrated in trying to use MoveIt for the ARIAC competition. The challenge to me is more than ROS answers can provide. I’ve worked through the MoveIt Melodic tutorial but still cannot translate it into working with the Universal Robots UR10 arms. I am determined to figure this out.

I’ve created a public moveit_tests repository on BitBucket that contains the MoveIt Tutorial, the Panda Arm, and the ARIAC version of the UR10 code as submodules. There is a standard repository ur10_tests that contains my attempts at using the UR10. There is a wiki explaining how to use the repository for your own experiments. I’m willing to add additional submodules for other robots if asked.

I’m hoping this can be a general resource that adds to the existing MoveIt material. The Wiki especially could be a useful place for adding explanations of working with MoveIt.

I’m willing to open it for others to work on this.

**Comment by 130s** [comment]
Closing as a potential duplicate, as this seems nearly identical to [this discussion on discourse](https://discourse.ros.org/t/workspace-for-testing-moveit/8617) and there's already an ongoing conversation there.
