### ISSUE TITLE
motion_planning_api Tutorial Hangs "Waiting for complete state from topic "

### ISSUE THREAD

**Issue by rmerriam** [ros-planning/moveit_tutorials#312]
### Description

The motion_planning_api Tutorial Hangs "Waiting for complete state from topic "

### Your environment
* ROS Distro: Melodic
* OS Version: e.g. Ubuntu 18.04
* Binary
* Using MoveIt Tutorials from Melodic:
`git submodule add -b melodic-devel https://github.com/ros-planning/moveit_tutorials.git
`

### Steps to reproduce
Terminal 1: roslaunch panda_moveit_config demo.launch
Terminal 2: roslaunch moveit_tutorials motion_planning_api_tutorial.launch

### Expected behaviour
Tell us what should happen

### Backtrace or Console output

[exec_motion_planning_api.txt](https://github.com/ros-planning/moveit_tutorials/files/3051123/exec_motion_planning_api.txt)
[rviz_motion_planning_api.txt](https://github.com/ros-planning/moveit_tutorials/files/3051124/rviz_motion_planning_api.txt)

**Comment by Dale-Koenig** [comment]
I fixed this by changing the virtual joint type in panda_moveit_config/config/panda_arm.xacro from "floating" to "fixed"

**Comment by rhaschke** [comment]
Assuming a fixed joint is one option to handle this.
The better way would be to _publish_ the corresponding transform, e.g. with a `static transform publisher`.

**Comment by rhaschke** [comment]
@mlautman, actually the roslaunch files should run the static transform publisher, shouldn't they?

**Comment by BryceStevenWilley** [comment]
This should have been fixed in https://github.com/ros-planning/panda_moveit_config/pull/23, but I have seen a lot of issues popping up about it lately. @Dale-Koenig, could you confirm that getting the latest commit from `panda_moveit_config` fixes this issue, without having to change the floating virtual joint type to fixed?

**Comment by Dale-Koenig** [comment]
@BryceStevenWilley The `virtual_joint_broadcaster_1` node exists but the same problem occurs.

**Comment by rhaschke** [comment]
Fixed via https://github.com/ros-planning/moveit_tutorials/pull/387.
