### ISSUE TITLE
moveit_tutorials error

### ISSUE THREAD

**Issue by npd26** [ros-planning/moveit_tutorials#349]
* ROS Distro: [Kinetic]
* OS Version: e.g. Ubuntu 16.04

Hello,

This is a question related to my post [http://answers.ros.org/question/327113/moveit_tutorials-kinetic-error/](url) as moveit_tutorials (kinetic) suddenly stop working which I am using since many months. can anyone help me to get this working again?

thanks.

**Comment by rhaschke** [comment]
Please be more patient and wait for answers on answers.ros.org.
