### ISSUE TITLE
Please add some clarifying info to MoveGroup tutorial

### ISSUE THREAD

**Issue by mcevoyandy** [ros-planning/moveit_tutorials#37]
I find these lines extremely confusing. Could someone could unpack them into something more readable / understandable? Maybe the first is a really efficient way to do it, but it doesn't seem appropriate for a tutorial. JointModelGroup and RobotModel aren't discussed at all so the tutorial also seems very incomplete.

offending lines:
https://github.com/ros-planning/moveit_tutorials/blob/kinetic-devel/doc/pr2_tutorials/planning/src/move_group_interface_tutorial.cpp#L145

https://github.com/ros-planning/moveit_tutorials/blob/kinetic-devel/doc/pr2_tutorials/planning/src/move_group_interface_tutorial.cpp#L187

This portion could also use some clarification:
https://github.com/ros-planning/moveit_tutorials/blob/indigo-devel/doc/pr2_tutorials/planning/src/move_group_interface_tutorial.cpp#L167

I had thought that `z_axis_tolerance = 3.14159` would mean that I just want the joint parallel to the floor, but making this change causes the solution to fail every time. What do these tolerances actually do and how would you use them to do something like "keep joint parallel to floor?"

**Comment by davetcoleman** [comment]
I can address this after this is merged: https://github.com/ros-planning/moveit_tutorials/pull/38

**Comment by davetcoleman** [comment]
https://github.com/ros-planning/moveit_tutorials/pull/42

I've cleaned up that tutorial, though I'm not sure what to say about the [axis constraints](https://github.com/ros-planning/moveit_tutorials/blob/indigo-devel/doc/pr2_tutorials/planning/src/move_group_interface_tutorial.cpp#L167) because I haven't used them.
