### ISSUE TITLE
Unable to 'catkin build'  with subframe issues

### ISSUE THREAD

**Issue by fcjscott** [ros-planning/moveit_tutorials#378]
### Description

As I'm trying to build the files, there's error showing "Collision object has no member named subframe_poses" and "subframe_names".

### Your environment
* ROS Distro: Melodic
* OS Version: e.g. Ubuntu 18.04
* Source or Binary build? Source

### Steps to reproduce
```mkdir -p ~/ws_moveit/src```
```cd ~/ws_moveit/src```
```git clone https://github.com/ros-planning/moveit_tutorials.git -b master```
```git clone https://github.com/ros-planning/panda_moveit_config.git -b melodic-devel```

**Comment by rhaschke** [comment]
Use also need to fetch the latest master from [`moveit_msgs`](https://github.com/ros-planning/moveit_msgs).
