### ISSUE TITLE
 MoveIt Tutorials error solution on Melodic ROS

### ISSUE THREAD

**Issue by Greg9914** [ros-planning/moveit_tutorials#384]
### Description

Hello,
I am here to inform a solution that I’ve discovered while installing MoveIt tutorials in ROS Melodic.
The message error happens after catkin_make , as it follows:

error: ‘moveit_msgs::CollisionObject {aka struct moveit_msgs::CollisionObject_<std::allocator >}’ has no member named ‘subframe_poses’; did you mean ‘plane_poses’?
box.subframe_poses.resize(5);

The error happens because the MoveIt tutorials uses a different version from Melodic (Kinetic I guess), thus, some code parts are different.

### Your environment
* ROS Distro: Melodic
* OS Version: e.g. Ubuntu 18.04.3

### Steps to reproduce
Go to ~/catkin_ws/src/moveit_tutorials/doc/subframes/src/subframes_tutorial.cpp
You’ll have to change every line containing the message:
box.subframes_names to box.id
box.subframes_poses to box.primitive_poses
and change the double quotation marks to single ones.
This helped me to finish the installation of MoveIt packages, and don’t forget to catkin_make after all this procedure.

### Expected behaviour
After the procedura, MoveIt tutorials packages should be installed in ~/catkin_ws/src folder, and might be working fine.

**Comment by rhaschke** [comment]
As it is indicated at the very top of each tutorial page, we have different versions of the tutorial depending on your specific ROS and MoveIt version. You tried to build the tutorials intended for the MoveIt `master` branch on the MoveIt binaries build from the `melodic` branch. This results in the error you observed and your "solution" is not at all valid.
Please, just use the correct tutorial version, i.e.
- for Melodic MoveIt binaries: [the melodic version](http://docs.ros.org/melodic/api/moveit_tutorials/html/doc/getting_started/getting_started.html)
- for Kinetic MoveIt binaries: [the kinetic version](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/getting_started/getting_started.html).
