### ISSUE TITLE
Error during roslaunch, problem in loading the robot

### ISSUE THREAD

**Issue by AlexPiantoni6** [ros-planning/moveit_tutorials#391]
### Description

[ERROR] [1567594659.061725310]: Exception while loading planning adapter plugin 'default_planner_request_adapters/ResolveConstraintFrames': According to the loaded plugin descriptions the class default_planner_request_adapters/ResolveConstraintFrames with base class type planning_request_adapter::PlanningRequestAdapter does not exist. Declared types are  default_planner_request_adapters/AddIterativeSplineParameterization default_planner_request_adapters/AddTimeOptimalParameterization default_planner_request_adapters/AddTimeParameterization default_planner_request_adapters/Empty default_planner_request_adapters/FixStartStateBounds default_planner_request_adapters/FixStartStateCollision default_planner_request_adapters/FixStartStatePathConstraints default_planner_request_adapters/FixWorkspaceBounds

when i add the "MotionPlanning" i see all the pieces of the panda arm in the same point

### Your environment
* ROS Distro: [Melodic]
* OS Version: e.g. Ubuntu 18.04
* Source or Binary build?
* If binary, which release version?
* If source, which git commit or tag?

### Steps to reproduce
I installed ubuntu 18.04, then I followed the instructions to install ros melodic and the catkin workspace, and finally the instructions on the tutorial moveit getting started

### Expected behaviour
All the pieces of the panda arm are accumulated in the same point

### Backtrace or Console output

Use [gist.github.com](gist.github.com) to copy-paste the console output or segfault backtrace using gdb.

**Comment by rhaschke** [comment]
The error you mentioned is probably unrelated to the problem that you see all links of the arm at the same point (probably the origin).
The former is related to the fact that the ResolveConstraintFrames was only recently added into the master branch of MoveIt.
The latter issue is an old URDF parsing issue related to your locale: https://github.com/ros-visualization/rviz/issues/1299. See there for a solution.
