### ISSUE TITLE
Using Cartesian paths to get at grasp pose

### ISSUE THREAD

**Issue by jediofgever** [ros-planning/moveit_tutorials#403]
### Description
I am trying out pick and place [tutorial](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/pick_place/pick_place_tutorial.html) 

when I set grasp pose, the robot always uses joint space method to get in grasp pose, which is undesired in my application, I had rather want the robot to get in grasp pose following a Cartesian path. It is straight forward to get  in grasp pose using `computeCartesian()`, but then again for using `moveit_msgs/Grasp.msg` the `grasp_pose` needs to be filled, 

I have tried to set  `grasp_pose`  to current pose after I move TCP to grasp pose using `computeCartesian() ` which should theoretically work, but I cant get it done.
Is there any suggestions or advice on how to get to the grasp pose following Cartesian path ? 

Your environment
* ROS Distro: [Kinetic]
* OS Version: Ubuntu 16.04
* Binary build

**Comment by mlautman** [comment]
@jediofgever Thanks for opening this question. As you have noticed, the pick and place pipeline isn't the most useful tool. There are two ongoing efforts to replace it that you may be interested in: the MoveIt Task Constructor and MoveIt Grasps. 

The ambiguity here seems to be surrounding the Grasp.msg where grasp_pose is the pose of your end effector when gripping the object. The Pick Action will take care of a Cartesian approach and retreat using `moveit_msgs/GripperTranslation pre_grasp_approach` and `moveit_msgs/GripperTranslation post_grasp_retreat`. 

This isn't really an issue with the tutorials so I'm going to close this issue. I would recommend opening a question on ROS answers.
