### ISSUE TITLE
Use of PlanningSceneMonitor never explained

### ISSUE THREAD

**Issue by Simon-Steinmann** [ros-planning/moveit_tutorials#412]
### Description

> 
> **Setup** 
> 
> The PlanningScene class can be easily setup and configured using a RobotModel or a URDF and SRDF. This is, however, not the recommended way to instantiate a PlanningScene. **The PlanningSceneMonitor is the recommended method** to create and maintain the current planning scene (and is discussed in detail in the next tutorial) using data from the robot’s joints and the sensors on the robot.

There is no explanation on how to use the PlanningSceneMonitor. I want to do collision checking with objects in the PlanningScene. There is nothing in the tutorial that shows me how to do that.

### Your environment
* ROS Distro: [melodic]
* OS Version: e.g. Ubuntu 18.04

**Comment by mlautman** [comment]
I agree that the documentation here is lacking and could certainly be better. As MoveIt and the tutorials are open source, I encourage you to make that contribution. The best way to understand how the pieces fit together is to go to the code for the PlanningSceneMonitor and seeing how it maintains an underlying PlanningScene using subscribers, diffs, locks, etc.. 

Once you understand the relationship between the two, please contribute back by expanding the documentation. In terms of examples to draw on for understanding how to do collision checking with setFromIK, look for examples in the MoveIt code base that create `robot_state::GroupStateValidityCallbackFn`s.
