### ISSUE TITLE
Realtime jogging tutorial often not shown

### ISSUE THREAD

**Issue by AndyZe** [ros-planning/moveit_tutorials#446]
The realtime jogging link often doesn't appear on the left side. It should be right under the joystick control teleoperation tutorial in this image.

![realtime_jogging_not_shown](https://user-images.githubusercontent.com/11284393/72447509-102b4e00-377b-11ea-9108-87b2d42e61fc.png)

**Comment by rhaschke** [comment]
This is a snapshot of the Kinetic tutorials. jog_arm is only part of master as I remember. The master tutorials have the link: https://ros-planning.github.io/moveit_tutorials.
