### ISSUE TITLE
Catkin build get "Jumpthreshold no matching function" error

### ISSUE THREAD

**Issue by frankiepham95** [ros-planning/moveit_tutorials#447]
I'm a newbie in Moveit!. I've followed this [tutorial](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/getting_started/getting_started.html). But at this step:
![image](https://user-images.githubusercontent.com/20719830/72668194-d0a08280-3a56-11ea-95f1-de4491558fa1.png)
I get this error:
![image](https://user-images.githubusercontent.com/20719830/72668216-1b21ff00-3a57-11ea-8798-ec5d47dfded2.png)
I have searched the error message but found nothing.
### My environment
* ROS Distro: Kinetic
* OS Version: e.g. Ubuntu 16.04

**Comment by rhaschke** [comment]
It looks like you mixed incompatible versions of MoveIt and the tutorials. Please checkout the kinetic-devel branch or melodic-devel or master for **both** of them. The kinetic build is working on Travis:
https://travis-ci.org/ros-planning/moveit_tutorials/builds/594716395
