### ISSUE TITLE
False numeric value for example of grasp_pose

### ISSUE THREAD

**Issue by YannickRiou** [ros-planning/moveit_tutorials#450]
### Description

There seems to be a little error on a numeric value on the pick and place tutorial explanation. 
In this tutorial for Kinetic (same for Melodic) : http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/pick_place/pick_place_tutorial.html at the paragraph "Setting grasp pose". It is written : "From panda_link8 to the palm of the eef the distance is 0.058, the cube starts 0.01 before **5.0** (half of the length of the cube).". The error is that the "5.0" value is false.

### Your environment
* ROS Distro: [Kinetic]
* OS Version: Ubuntu 16.04

### Expected behaviour
I think the correct value might be "0.5" as there is nothing at 5 meters from the panda robot and also the value "grasps[0].grasp_pose.pose.position.x = 0.415;" in the code confirm that it is just a comma error. 

Also if I may, I find the sentence a bit tricky to understand (in my opinion). Can we rephrase it this way : "From panda_link8 to the palm of the eef, the distance is 0.058. The cube starts at 0.01 (half the length of the cube)." 
And also to be correct, the following equation must be " Therefore, the position for panda_link8 = 5 - length of cube/2 - distance b/w panda_link8 and palm of eef - some extra padding" without the parenthesis or it would have meant "panda_link8 = 5 - length of cube/2 + distance b/w panda_link8 and palm of eef + some extra padding" 

Regards,

**Comment by mlautman** [comment]
Fixed in #451 where I remove the incorrect information. In the future, feel free to open a PR with your suggestions rather than opening an issue. 

Depending on your project, I would recommend using the moveit_task_constructor rather than the pick and place pipeline. The pick and place pipeline is in the process of getting phased out.
