### ISSUE TITLE
Can I use move_group_python_interface_tutorial.py to move Panda in RViz and simultaneously in Gazebo?

### ISSUE THREAD

**Issue by MatteoL95** [ros-planning/moveit_tutorials#482]
Hi, I'm new to ROS, RViz and Gazebo and I'm tryng to command Panda in RViz and simultaneously in Gazebo for my thesis project.
I must plan and execute a goal pose for Panda in RViz and simultaneously in Gazebo using a script and I'd like to try starting by move_group_pyhton_interface_tutorial.py and after write my personal script.

Someone can help me??

My configuration:
* ROS Distro: Melodic
* OS Version: Ubuntu 18.04

For me it's the first time on GitHub and I hope to find help.

Thanks

P.S. I hope I put my question in the right section and in the right way.
If not, I apologize and ask someone to redirect me on where and how to ask this question to find help.

**Comment by felixvd** [comment]
Late response because no one watches this repository for user support. Posting a detailed question on ROS Answers detailing what you have tried is the best way to get support.

Closing because this is a homework question and outdated.
