### ISSUE TITLE
visual_tools.publishTrajectoryLine does not show anything

### ISSUE THREAD

**Issue by blackhorsewu** [ros-planning/moveit_tutorials#509]
### Description

Followed the move_group C++ interface successfully. However, there is no trajectory show up after planning.

### Your environment
* ROS Distro: Melodic
* OS Version: Ubuntu 18.04
* Source or Binary build? Source
* If binary, which release version?
* If source, which git commit or tag?

### Steps to reproduce
Tell us how to reproduce this issue. Attempt to provide a working demo, perhaps using Docker.

### Expected behaviour
Tell us what should happen

### Backtrace or Console output

Use [gist.github.com](gist.github.com) to copy-paste the console output or segfault backtrace using gdb.

**Comment by felixvd** [comment]
I'll close this for inactivity (I also can't reproduce the problem), but feel free to reopen if it persists.
