### ISSUE TITLE
motion_planning_api is broken due to update

### ISSUE THREAD

**Issue by gbcarlos** [ros-planning/moveit_tutorials#510]
### Description

Hi,

While trying to start the motion planning api tutorial with `roslaunch moveit_tutorials motion_planning_api_tutorial.launch` I get the error that there is no file called libmoveit_planning_scene.so.1.0.3 which is correct because the file has been updated to 1.0.4. Now I don't know from which file the files are being called so I can't fix this on my own. This issue affects also the Planning Scene tutorial and probably othes too. 

### Your environment
* ROS Distro: Melodic
* OS Version: Ubuntu 18.04
* Source

### Steps to reproduce
Follow the getting started steps to setup moveit workspace, then follow steps from motion planning api tutorial.

### Expected behaviour
4 trajectories should be displayed

### Backtrace or Console output

process[planning_scene_tutorial-1]: started with pid [8289]
**/home/carlos/ws_moveit/devel/lib/moveit_tutorials/planning_scene_tutorial: error while loading shared libraries: libmoveit_planning_scene.so.1.0.3: cannot open shared object file: No such file or directory**
[planning_scene_tutorial-1] process has died [pid 8289, exit code 127, cmd /home/carlos/ws_moveit/devel/lib/moveit_tutorials/planning_scene_tutorial __name:=planning_scene_tutorial __log:=/home/carlos/.ros/log/b1915d74-d7cc-11ea-9e09-f85971f581ec/planning_scene_tutorial-1.log].
log file: /home/carlos/.ros/log/b1915d74-d7cc-11ea-9e09-f85971f581ec/planning_scene_tutorial-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by rhaschke** [comment]
Just rebuild your workspace comprising the moveit_tutorials and you should be fine.
