### ISSUE TITLE
execute panda_moveit_config/demo.launch error

### ISSUE THREAD

**Issue by hfr2015** [ros-planning/moveit_tutorials#513]
### Description

When I execute "roslaunch panda_moveit_config demo.launch rviz_tutorial:=true", I get the error:" [ERROR] [1597131572.798831078]: Exception while loading move_group capability 'move_group/MoveGroupExecuteService': MultiLibraryClassLoader: Could not create object of class type move_group::MoveGroupExecuteService as no factory exists for it. Make sure that the library exists and was explicitly loaded through MultiLibraryClassLoader::loadLibrary()"

### Your environment
* ROS Distro: Melodic
* OS Version: e.g. Ubuntu 18.04
* Source or Binary build?
source build
geometric_shapes：noetic-devel
moveit：master
moveit_msgs：master
moveit_tutorials：master
moveit_visual_tools：master
panda_moveit_config：melodic-devel
rviz_visual_tools：master

### Steps to reproduce
execute by：
1.https://ros-planning.github.io/moveit_tutorials/doc/getting_started/getting_started.html
2.https://ros-planning.github.io/moveit_tutorials/doc/quickstart_in_rviz/quickstart_in_rviz_tutorial.html

### Backtrace or Console output

rviz can not add motionplanning，stucked

**Comment by rhaschke** [comment]
I cannot confirm this issue with a recent version of `[panda_moveit_config](https://github.com/ros-planning/panda_moveit_config)`.
The `MoveGroupExecuteService` was replaced with `MoveGroupExecuteTrajectoryAction` a long time ago...
Please update and try again.
