### ISSUE TITLE
Run moveit_cpp_tutorial.launch demo and debug it with VS Code

### ISSUE THREAD

**Issue by gautz** [ros-planning/moveit_tutorials#515]
### Description

Trying to run the moveitcpp demo from https://ros-planning.github.io/moveit_tutorials/doc/moveit_cpp/moveitcpp_tutorial.html
I am getting following error when clicking on the button "next":
```
[ INFO] [1597766286.921420928]: Failed to call service get_planning_scene, have you launched move_group or called psm.providePlanningSceneService()?
... continuing
[ERROR] [1597766300.807926139]: No planning pipeline available for name ''
```

I am also not able to debug the launch file for any MoveIt tutorial from VS code following https://github.com/ms-iot/vscode-ros/blob/master/doc/debug-support.md#launch

### Your environment
* ROS Distro: [Melodic] 1.14.7
* OS Version: Ubuntu 18.04 **VirtualBox**
* MoveIt from master branch: commit 589f83a132da174991b233931d3ca7f31ab1cba4

### Steps to reproduce
Install from MoveIt from source following https://ros-planning.github.io/moveit_tutorials/doc/moveit_cpp/moveitcpp_tutorial.html

Run the demo:
``roslaunch moveit_tutorials moveit_cpp_tutorial.launch .``

### Expected behaviour
Path is planned with OMPL using the moveit cpp interface. Robot moves.

### Backtrace or Console output
https://gist.github.com/gautz/41c3ef6a8fefc18b2a842cdc175c825e

**Comment by JafarAbdi** [comment]
@gautz Thanks for reporting this, https://github.com/ros-planning/moveit_tutorials/pull/516 should fix it, the parameter namespace was changed in https://github.com/ros-planning/moveit/pull/2033
