### ISSUE TITLE
Create tutorial for using mesh filter

### ISSUE THREAD

**Issue by davetcoleman** [ros-planning/moveit_tutorials#524]
The mesh filter takes in a point cloud, tf of robot, and a URDF and publishes a modified point cloud with the point cloud subtracted that overlaps with the current robot state. However, there isn't a tutorial on how to do this. I know it worked years ago, as I used it then:
https://github.com/ros-planning/moveit/tree/master/moveit_ros/perception/mesh_filter

We need a tutorial for this!

Note the feature is mentioned in this page briefly: https://moveit.ros.org/documentation/concepts/

**Comment by JStech** [comment]
#558
