### ISSUE TITLE
About Inverse Kinematics, I can only get  one IK solution by kinematic_state->setFromIK().

### ISSUE THREAD

**Issue by jinghehyh** [ros-planning/moveit_tutorials#526]
### Description

The function kinematic_state->setFromIK() can only get one IK solution. For UR manipulator, there are usually 8 IK solution. How can I get all solutions?

**Comment by mlautman** [comment]
If you look at the kinematics base class in moveit you will find that getting all solutions for an IK pose isn't as straightforward as you might hope. That said, so long as your kinematic solver supports getting all the results, you should find the api call you are looking for in there. 

Thanks for your question :)
