### ISSUE TITLE
Issue/Request for Tutorial/Doc of Pick and Place

### ISSUE THREAD

**Issue by kappa95** [ros-planning/moveit_tutorials#528]
### Tutorial&Doc Pick and Place

I was following the tutorials and documentation for the ROS Kinetic, particularly the one related to Python Interface.
Is it possible to add the documentation and tutorial for grasping using Python? 
Or in case can you link some guide/tutorials? 
Thank you so much

### Your environment
* ROS Distro: Kinetic
* OS Version: Ubuntu 16.04

**Comment by mlautman** [comment]
@kappa95 This is not a bug, it is a feature request. As you learn about pick and place in python, please add documentation and fixes where they are needed. Future MoveIt users (including future you) will appreciate it :)
