### ISSUE TITLE
Embedded video broken

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit_tutorials#535]
### Description

I experience this on the master branch version of the tutorials in Firefox 81.0 on Ubuntu 20.04.  I'm not sure how to fix it.  If I click on the link I can watch the video, I imagine the intent was to have that video embedded in the page, not a link.

![embedded_video_broken](https://user-images.githubusercontent.com/2490389/94997639-c7663000-0569-11eb-838c-2e25f0d54e0b.png)

**Comment by felixvd** [comment]
Related: #474

**Comment by felixvd** [comment]
@tylerjw This now works for me on Chrome/MacOS and Firefox 85 on Ubuntu 20.04, so I assume it's fixed by #550
