### ISSUE TITLE
How to get the goal state of Rviz by programming?

### ISSUE THREAD

**Issue by LMNcnu** [ros-planning/moveit_tutorials#55]
In the Rviz, I drag the marker on an arm of robot, then the orange color represent the goal state. How to get the goal state of Rviz by programming?
![image](https://cloud.githubusercontent.com/assets/16238857/21603132/c9e8cb06-d1d5-11e6-901b-b7835621d383.png)

**Comment by davetcoleman** [comment]
Create your own [interactive markers](http://wiki.ros.org/interactive_markers) and connect to an IK solver using custom code. Or use my pre-made version available in [moveit_visual_tools](https://github.com/ros-planning/moveit_visual_tools/blob/kinetic-devel/include/moveit_visual_tools/imarker_robot_state.h)

**Comment by LMNcnu** [comment]
Hi，I want to get the orange arm's state(just every joint's angle), could you tell me?
Because the orange's arm is goal state ，is not current state. So I can't get the state by move_group.getCurrentState().

**Comment by davetcoleman** [comment]
You will need to create your own solution (see above comment of mine) because the GUI you are referring to is not intended to be used along with custom code.

**Comment by LMNcnu** [comment]
OK，thanks
