### ISSUE TITLE
Robot Pose option did not show and tutorial problem

### ISSUE THREAD

**Issue by Sission** [ros-planning/moveit_tutorials#553]
### Description

I set the home position in Step 5: Add Robot Poses. However, when I run $ roslaunch panda_moveit_config demo.launch. My named home position does not show in my "start state" and "goal state". (I picked the right planning group).

Another problem is in Step 4: Add Planning Groups:
For the gripper, the text says "Add Link". However, the figure attached shows it was added as "Joints"

### Your environment
* ROS Distro: Melodic
* OS Version: e.g. Ubuntu 18.04
* Binary build

**Comment by rhaschke** [comment]
This issue section is for bug reports, not for help requests. 
Please direct questions to https://answers.ros.org.
