### ISSUE TITLE
Problem: [demo.launch] is neither a launch file in package

### ISSUE THREAD

**Issue by jordane520** [ros-planning/moveit_tutorials#562]
### Description:
I follow the "MoveIt Setup Assistant tutorial". 
In the final step, I send roslaunch panda_moveit_config demo.launch rviz_tutorial:=true
Then receive:
RLException: [demo.launch] is neither a launch file in package [panda_moveit_config] nor is [panda_moveit_config] a launch file name
The traceback for the exception was written to the log file.

I also follow the ROS tutorial.  source /opt/ros/neotic/setup.bash. But it is the same.
I save panda_moveit_config folder in  $HOME/panda_moveit_config.
The panda_moveit_config folder contains two folders: config and launch. And two files: CmakeLists and package.xml
I can't catkin_make this package.

What should I do?

### Myenvironment
* ROS Distro:  Noetic
* OS Version: e.g. Ubuntu 20.04
* Moveit Version:  ros-noetic-moveit

**Comment by mlautman** [comment]
Please be sure to source your workspace correctly. I can almost guarantee this is your issue. Please re-open if you continue to experience this issue.
