### ISSUE TITLE
How to get the goal state of Rviz by programming?

### ISSUE THREAD

**Issue by LMNcnu** [ros-planning/moveit_tutorials#57]
https://github.com/ros-planning/moveit_tutorials/issues/55

Hi，bother again，I want to get the orange arm's state(just every joint's angle), could you tell me?
Because the orange's arm is goal state ，is not current state. So I can't get the state by move_group.getCurrentState().
Thanks！

**Comment by davetcoleman** [comment]
Please only post this question in one issue for MoveIt!

**Comment by LMNcnu** [comment]
OK，i got it
