### ISSUE TITLE
possible problem with orientation in all_close() check

### ISSUE THREAD

**Issue by mqnc** [ros-planning/moveit_tutorials#574]
https://github.com/ros-planning/moveit_tutorials/blob/fff33d2b73af1d07ba329bbb0fceb9cb1c48edc0/doc/move_group_python_interface/scripts/move_group_python_interface_tutorial.py#L67

this will fail on opposite quaternions which represent the same orientation

or is it guaranteed that the w component is always positive?

**Comment by YijiongLin** [comment]
In a unit quaternion, the w should always be a positive one.  See [here](https://en.wikipedia.org/wiki/Quaternions_and_spatial_rotation).

![image](https://user-images.githubusercontent.com/26537492/104858818-b9ba9780-5919-11eb-8d65-4dd462be1409.png)

And the w here actually is the real part of the quaternion. You can read more in the method: `geometry_msgs.msg.Quaternion()`

**Comment by rhaschke** [comment]
The only limitation for unit quaternions is to be normalized to one. Particularly, it is possible to represent the very same rotation by q and -q. So yes, @mqnc's objection is correct, that `all_close` will fail for quaternions q and -q, although they represent the same orientation. @mqnc, did you observe any issues due to this shortcoming?

**Comment by mqnc** [comment]
@rhaschke yes, I observed the issue that I cannot sleep well anymore since I've seen this. This is a tutorial which is supposed to show people how things are done properly. They will use this code as a template and it will run in industrial and medical applications. I can provide a pull request to fix this.

**Comment by mqnc** [comment]
https://github.com/ros-planning/moveit_tutorials/pull/577

**Comment by mlautman** [comment]
closing now that #577 is merged
