### ISSUE TITLE
typo "hueristics"

### ISSUE THREAD

**Issue by ndehio** [ros-planning/moveit_tutorials#580]
I found a minor typo in this [paragraph](http://docs.ros.org/en/melodic/api/moveit_tutorials/html/doc/ompl_interface/ompl_interface_tutorial.html#determinism):
"tuning special hueristics" -> heuristics

**Comment by rhaschke** [comment]
Thanks for pointing this out. A PR would have been even more welcome :wink: I fixed it in melodic-devel now, on master this typo was fixed already.
