### ISSUE TITLE
[move_group-7] process has died. Error code= -11

### ISSUE THREAD

**Issue by lucasrebra** [ros-planning/moveit_tutorials#588]
### Description
I installed ROS in my raspberry using the ubiquity robotics image. It works fine but now Im trying to launch the movegroup following a tutorial and is giving me that eror. I fund some issues related but I still don't understand what's happening. 

I'm working in a raspberry pi 4, so I think this mustn't be the problem.

### Your environment
* ROS Distro: [Kinetic]
* OS Version: e.g. Ubuntu 16.04
* Binary 
* If binary, which release version? Last version

### Steps to reproduce
I just install the moveit binary and install the controllers and launch the launch file which contains this for launching the move group:

	
	 <node name="joint_state_publisher" pkg="joint_state_publisher" type="joint_state_publisher">
		<param name="use_gui" value="false"/>
		<rosparam param="/source_list">[/move_group]</rosparam>
	 </node>

### Expected behaviour
I'm using a program that runs in my pc in the VM so have to woek the move_group and could interact with it using scripts via python API or by using custom nodes.

### Backtrace or Console output

[move_group-7] process has died [pid 5651, exit code -11, cmd /opt/ros/kinetic/lib/moveit_ros_move_group/move_group __name:=move_group __log:=/home/ubuntu/.ros/log/6e70a654-d0dc-11e5-b36d-f7f145135473/move_group-7.log].
log file: /home/ubuntu/.ros/log/6e70a654-d0dc-11e5-b36d-f7f145135473/move_group-7*.log

**Comment by mlautman** [comment]
This is a rather esoteric use case that isn't supported. For that reason, I'm going to close this PR for now. If you get the same error with a more simple setup (pc running ubuntu natively) feel free to re-open. Also, if you do find a solution, please describe it here or open a PR with the fix.
