### ISSUE TITLE
Replace "MoveIt!" with "MoveIt" in kinetic-devel

### ISSUE THREAD

**Issue by felixvd** [ros-planning/moveit_tutorials#593]
Just find+replace all the occurrences of the old "MoveIt!" name with the new ("MoveIt"). Just simple housekeeping.

**Comment by ChaxuGarg** [comment]
Can I work on this issue?

**Comment by DLu** [comment]
@ChaxuGarg There is a PR already with #596 

@felixvd I disagree on principle, but it does match with proper branding.

**Comment by felixvd** [comment]
Fixed by #596
