### ISSUE TITLE
Err while movint right_arm in "Move Group Python Interface Tutorial"

### ISSUE THREAD

**Issue by ipesanz** [ros-planning/moveit_tutorials#62]
Hi,

I was doing some tests with this file:
https://github.com/ros-planning/moveit_tutorials/blob/kinetic-devel/doc/pr2_tutorials/planning/scripts/move_group_python_interface_tutorial.py

And in line 76 where you chose which arm do you want to use (right or left) there is some strange behaviour when you change from left to right_arm

After changing this arm, on the 2nd visualization the program FAILS with this output:

```
Traceback (most recent call last):
  File "./group2.py", line 238, in <module>
    move_group_python_interface_tutorial()
  File "./group2.py", line 175, in move_group_python_interface_tutorial
    group.set_joint_value_target(group_variable_values)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/moveit_commander/move_group.py", line 196, in set_joint_value_target
    raise MoveItCommanderException("Error setting joint target. Is the target within bounds?")
moveit_commander.exception.MoveItCommanderException: Error setting joint target. Is the target within bounds?
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
```

The program is only able to run plan1 with the option (right_arm) as I mentioned before

**Comment by 130s** [comment]
I suggest a technical question like this to be asked on http://answers.ros.org where you can get more exposure to the active developers, with more info for platform, version of relevant software (`moveit` etc.)
