### ISSUE TITLE
How to setup moveit for effort_controllers/JointPositionController controller.

### ISSUE THREAD

**Issue by Infinity8sailor** [ros-planning/moveit_tutorials#650]
### Description

I know steps involved for position_controllers, as they provide FollowJointTrajectory Topics which moveit search for.
But in case of effort_controllers/JointPositionController controller, we get controller/command and controller/state on rostopic list.
im not getting proper documentation to set it uo properly.

### Your environment
* ROS Distro: Melodic
* OS Version: e.g. Ubuntu 18.04
* Source or Binary build?
* If binary, which release version?
* If source, which git commit or tag?

**Comment by v4hn** [comment]
The `FollowJointTrajectory` action is provided by the [`joint_trajectory_controller`](https://wiki.ros.org/joint_trajectory_controller) which also runs on top of `effort_controllers/JointPositionController`.

If you don't have any kind of position tracking enabled with your system though, you can't execute trajectories planned through moveit.
On the other hand, as long as you can send velocity targets, you can interface with `moveit_servo`, but that does not seem to be what you want to do.
