### ISSUE TITLE
RobotCommander vs MoveGroupCommander

### ISSUE THREAD

**Issue by theotromp97** [ros-planning/moveit_tutorials#690]
### Description

I was looking at the tutorials of moveit! (link) and was wondering the following:

What is the difference between moveit_commander, moveit_interface and robot_commander 

The tutorial states the following: 
Robotcommander --> Instantiate a RobotCommander object. Provides information such as the robot’s kinematic model and the robot’s current joint states
MoveGroupCommander --> Instantiate a MoveGroupCommander object. This object is an interface to a planning group (group of joints). 

Looking on the internet i see a lot of examples using only one of the two,
Which one do I use at what time?

Thanks in advance

**Comment by rhaschke** [comment]
`MoveGroupCommander` is used to interface a _single_ planning group. It is needed for any kind of planning operation.
`RobotCommander` is an abstraction of the full URDF/SRDF, comprising _all_ planning groups of your robot.
Given a `RobotCommander` instance `robot`, you can access its groups (i.e. _instances_ of `MoveGroupCommander`) via:
```python
robot.get_group('my_group')
robot.my_group
```
Please consider filing a PR to improve the python tutorials. Your inputs are highly welcome.
