### ISSUE TITLE
Position_controllers/JointPositionController is missing from the moveit setup assistant.

### ISSUE THREAD

**Issue by sm3304love** [ros-planning/moveit_tutorials#698]
### Description

After updating to ubuntu 20.04, I tried to create a new config file using moveit setup assistance. However, position_controllers/JointTrajectoryController was identified in the ROS Control pane selector, but position_controllers/JointPositionController was missing.

### Your environment
* ROS Distro: [noetic]
* OS Version:  Ubuntu 20.04

### Steps to reproduce
https://ros-planning.github.io/moveit_tutorials/doc/setup_assistant/setup_assistant_tutorial.html

I followed the link above to proceed with the movement setup assistant tutorial.

### Expected behaviour
Select Position_controllers/Joint Position Controller from the ROS Control pane selector.

###Actual behaviour
Position_controllers/JointPositionController does not exist in the option.
![image](https://user-images.githubusercontent.com/57741032/150645758-974406c6-00b5-400a-8cf4-1e230823fe10.png)

**Comment by JafarAbdi** [comment]
It was removed by https://github.com/ros-planning/moveit/pull/2945/commits/c56d86a4dbf867f09e6392be01b3804ea76343f0, @rhaschke should I update the tutorials to reflect the change ?

**Comment by sm3304love** [comment]
> It was removed by [ros-planning/moveit@c56d86a](https://github.com/ros-planning/moveit/commit/c56d86a4dbf867f09e6392be01b3804ea76343f0), @rhaschke should I update the tutorials to reflect the change ?

Yes, currently, the tutorial is explaining based on the old version.

**Comment by rhaschke** [comment]
> It was removed by [ros-planning/moveit@c56d86a](https://github.com/ros-planning/moveit/commit/c56d86a4dbf867f09e6392be01b3804ea76343f0), @rhaschke should I update the tutorials to reflect the change?

Yes, it would be great if you could validate and update the tutorial if necessary.
For now, just use the `position_controllers/JointTrajectoryController`.

**Comment by sm3304love** [comment]
> > It was removed by [ros-planning/moveit@c56d86a](https://github.com/ros-planning/moveit/commit/c56d86a4dbf867f09e6392be01b3804ea76343f0), @rhaschke should I update the tutorials to reflect the change?
> 
> Yes, it would be great if you could validate and update the tutorial if necessary. @sm3304love, for now, just use the `position_controllers/JointTrajectoryController`.

Thank you. It helped solve the problem.
