### ISSUE TITLE
Error in building moveit_tutorial package using catkin_make

### ISSUE THREAD

**Issue by AMAN021jin** [ros-planning/moveit_tutorials#716]
* ROS Distro: Melodic
* OS Version: e.g. Ubuntu 18.04

adminspin@adminspin:~/catkin_ws$ catkin_make
Base path: /home/adminspin*/catkin_ws
Source space: /home/adminspin*/catkin_ws/src
Build space: /home/adminspin*/catkin_ws/build
Devel space: /home/adminspin*/catkin_ws/devel
Install space: /home/adminspin*/catkin_ws/install
Creating symlink "/home/adminspin*/catkin_ws/src/CMakeLists.txt" pointing to "/opt/ros/melodic/share/catkin/cmake/toplevel.cmake"
####
####
-- The C compiler identification is Clang 9.0.0
-- The CXX compiler identification is Clang 9.0.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /home/adminspin*/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /home/adminspin*/catkin_ws/devel;/opt/ros/melodic
-- This workspace overlays: /home/adminspin*/catkin_ws/devel;/opt/ros/melodic
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.17", minimum required is "2") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/adminspin*/catkin_ws/build/test_results
-- Forcing gtest/gmock from source, though one was otherwise available.
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.17") 
-- Found Threads: TRUE  
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.29
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 3 packages in topological order:
-- ~~  - panda_moveit_config
-- ~~  - beginner_tutorials
-- ~~  - moveit_tutorials
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'panda_moveit_config'
-- ==> add_subdirectory(panda_moveit_config)
-- +++ processing catkin package: 'beginner_tutorials'
-- ==> add_subdirectory(beginner_tutorials)
-- +++ processing catkin package: 'moveit_tutorials'
-- ==> add_subdirectory(moveit_tutorials)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
--   filesystem
--   date_time
--   thread
--   chrono
--   atomic
-- Configuring done
CMake Warning at moveit_tutorials/doc/controller_configuration/CMakeLists.txt:1 (add_library):
  Cannot generate a safe runtime search path for target
  controller_manager_example because files in some directories may conflict
  with libraries in implicit directories:

    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.

CMake Warning at moveit_tutorials/doc/interactivity/CMakeLists.txt:3 (add_library):
  Cannot generate a safe runtime search path for target interactivity_utils
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.

CMake Warning at moveit_tutorials/doc/kinematics/CMakeLists.txt:1 (add_executable):
  Cannot generate a safe runtime search path for target ros_api_tutorial
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.

CMake Warning at moveit_tutorials/doc/motion_planning_api/CMakeLists.txt:1 (add_executable):
  Cannot generate a safe runtime search path for target
  motion_planning_api_tutorial because files in some directories may conflict
  with libraries in implicit directories:

    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.

CMake Warning at moveit_tutorials/doc/motion_planning_pipeline/CMakeLists.txt:1 (add_executable):
  Cannot generate a safe runtime search path for target
  motion_planning_pipeline_tutorial because files in some directories may
  conflict with libraries in implicit directories:

    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.

CMake Warning at moveit_tutorials/doc/move_group_interface/CMakeLists.txt:1 (add_executable):
  Cannot generate a safe runtime search path for target
  move_group_interface_tutorial because files in some directories may
  conflict with libraries in implicit directories:

    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.

CMake Warning at moveit_tutorials/doc/perception_pipeline/CMakeLists.txt:4 (add_executable):
  Cannot generate a safe runtime search path for target
  bag_publisher_maintain_time because files in some directories may conflict
  with libraries in implicit directories:

    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.

CMake Warning at moveit_tutorials/doc/pick_place/CMakeLists.txt:1 (add_executable):
  Cannot generate a safe runtime search path for target pick_place_tutorial
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.

CMake Warning at moveit_tutorials/doc/planning_scene/CMakeLists.txt:1 (add_executable):
  Cannot generate a safe runtime search path for target
  planning_scene_tutorial because files in some directories may conflict with
  libraries in implicit directories:

    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.

CMake Warning at moveit_tutorials/doc/planning_scene_ros_api/CMakeLists.txt:1 (add_executable):
  Cannot generate a safe runtime search path for target
  planning_scene_ros_api_tutorial because files in some directories may
  conflict with libraries in implicit directories:

    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.

CMake Warning at moveit_tutorials/doc/robot_model_and_robot_state/CMakeLists.txt:1 (add_executable):
  Cannot generate a safe runtime search path for target
  robot_model_and_robot_state_tutorial because files in some directories may
  conflict with libraries in implicit directories:

    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.

CMake Warning at moveit_tutorials/doc/state_display/CMakeLists.txt:1 (add_executable):
  Cannot generate a safe runtime search path for target
  state_display_tutorial because files in some directories may conflict with
  libraries in implicit directories:

    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.

CMake Warning at moveit_tutorials/doc/subframes/CMakeLists.txt:1 (add_executable):
  Cannot generate a safe runtime search path for target subframes_tutorial
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.

CMake Warning at /opt/ros/melodic/share/catkin/cmake/test/gtest.cmake:180 (add_executable):
  Cannot generate a safe runtime search path for target tests_tutorial
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  /opt/ros/melodic/share/catkin/cmake/test/gtest.cmake:89 (_catkin_add_executable_with_google_test)
  /opt/ros/melodic/share/catkin/cmake/test/gtest.cmake:37 (_catkin_add_google_test)
  moveit_tutorials/doc/tests/CMakeLists.txt:2 (catkin_add_gtest)

CMake Warning at moveit_tutorials/doc/trajopt_planner/CMakeLists.txt:1 (add_executable):
  Cannot generate a safe runtime search path for target trajopt_example
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.

CMake Warning at moveit_tutorials/doc/creating_moveit_plugins/lerp_motion_planner/CMakeLists.txt:8 (add_executable):
  Cannot generate a safe runtime search path for target lerp_example because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.

CMake Warning at moveit_tutorials/doc/creating_moveit_plugins/lerp_motion_planner/CMakeLists.txt:15 (add_library):
  Cannot generate a safe runtime search path for target
  moveit_lerp_planner_plugin because files in some directories may conflict
  with libraries in implicit directories:

    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.

CMake Warning at moveit_tutorials/doc/moveit_cpp/CMakeLists.txt:1 (add_executable):
  Cannot generate a safe runtime search path for target moveit_cpp_tutorial
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.

CMake Warning at moveit_tutorials/doc/visualizing_collisions/CMakeLists.txt:1 (add_executable):
  Cannot generate a safe runtime search path for target
  visualizing_collisions_tutorial because files in some directories may
  conflict with libraries in implicit directories:

    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.

CMake Warning at moveit_tutorials/doc/bullet_collision_checker/CMakeLists.txt:1 (add_executable):
  Cannot generate a safe runtime search path for target
  bullet_collision_checker_tutorial because files in some directories may
  conflict with libraries in implicit directories:

    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.

-- Generating done
-- Build files have been written to: /home/adminspin*/catkin_ws/build
####
####
Scanning dependencies of target controller_manager_example
Scanning dependencies of target ros_api_tutorial
Scanning dependencies of target interactivity_utils
Scanning dependencies of target motion_planning_api_tutorial
Scanning dependencies of target move_group_interface_tutorial
Scanning dependencies of target detect_and_add_cylinder_collision_object_demo
Scanning dependencies of target bag_publisher_maintain_time
Scanning dependencies of target motion_planning_pipeline_tutorial
[  2%] Building CXX object moveit_tutorials/doc/controller_configuration/CMakeFiles/controller_manager_example.dir/src/moveit_controller_manager_example.cpp.o
[  4%] Building CXX object moveit_tutorials/doc/perception_pipeline/CMakeFiles/bag_publisher_maintain_time.dir/src/bag_publisher_maintain_time.cpp.o
[  6%] Building CXX object moveit_tutorials/doc/kinematics/CMakeFiles/ros_api_tutorial.dir/src/ros_api_tutorial.cpp.o
[  9%] Building CXX object moveit_tutorials/doc/interactivity/CMakeFiles/interactivity_utils.dir/src/interactive_robot.cpp.o
[ 11%] Building CXX object moveit_tutorials/doc/motion_planning_api/CMakeFiles/motion_planning_api_tutorial.dir/src/motion_planning_api_tutorial.cpp.o
[ 13%] Building CXX object moveit_tutorials/doc/perception_pipeline/CMakeFiles/detect_and_add_cylinder_collision_object_demo.dir/src/detect_and_add_cylinder_collision_object_demo.cpp.o
[ 15%] Building CXX object moveit_tutorials/doc/move_group_interface/CMakeFiles/move_group_interface_tutorial.dir/src/move_group_interface_tutorial.cpp.o
[ 18%] Building CXX object moveit_tutorials/doc/motion_planning_pipeline/CMakeFiles/motion_planning_pipeline_tutorial.dir/src/motion_planning_pipeline_tutorial.cpp.o
[ 20%] Linking CXX shared library "/home/adminspin*/catkin_ws/devel/lib/libcontroller_manager_example.so"
[ 20%] Built target controller_manager_example
Scanning dependencies of target pick_place_tutorial
[ 22%] Linking CXX executable "/home/adminspin*/catkin_ws/devel/lib/moveit_tutorials/bag_publisher_maintain_time"
[ 25%] Building CXX object moveit_tutorials/doc/pick_place/CMakeFiles/pick_place_tutorial.dir/src/pick_place_tutorial.cpp.o
[ 27%] Linking CXX executable "/home/adminspin*/catkin_ws/devel/lib/moveit_tutorials/ros_api_tutorial"
[ 29%] Building CXX object moveit_tutorials/doc/interactivity/CMakeFiles/interactivity_utils.dir/src/imarker.cpp.o
[ 29%] Built target bag_publisher_maintain_time
Scanning dependencies of target planning_scene_tutorial
[ 31%] Building CXX object moveit_tutorials/doc/planning_scene/CMakeFiles/planning_scene_tutorial.dir/src/planning_scene_tutorial.cpp.o
[ 34%] Linking CXX executable "/home/adminspin*/catkin_ws/devel/lib/moveit_tutorials/move_group_interface_tutorial"
[ 36%] Linking CXX executable "/home/adminspin*/catkin_ws/devel/lib/moveit_tutorials/motion_planning_pipeline_tutorial"
[ 36%] Built target ros_api_tutorial
Scanning dependencies of target planning_scene_ros_api_tutorial
[ 38%] Building CXX object moveit_tutorials/doc/planning_scene_ros_api/CMakeFiles/planning_scene_ros_api_tutorial.dir/src/planning_scene_ros_api_tutorial.cpp.o
[ 40%] Linking CXX executable "/home/adminspin*/catkin_ws/devel/lib/moveit_tutorials/motion_planning_api_tutorial"
[ 43%] Linking CXX executable "/home/adminspin*/catkin_ws/devel/lib/moveit_tutorials/pick_place_tutorial"
[ 43%] Built target move_group_interface_tutorial
Scanning dependencies of target robot_model_and_robot_state_tutorial
[ 45%] Building CXX object moveit_tutorials/doc/robot_model_and_robot_state/CMakeFiles/robot_model_and_robot_state_tutorial.dir/src/robot_model_and_robot_state_tutorial.cpp.o
[ 47%] Building CXX object moveit_tutorials/doc/interactivity/CMakeFiles/interactivity_utils.dir/src/pose_string.cpp.o
[ 47%] Built target motion_planning_pipeline_tutorial
Scanning dependencies of target state_display_tutorial
[ 50%] Building CXX object moveit_tutorials/doc/state_display/CMakeFiles/state_display_tutorial.dir/src/state_display_tutorial.cpp.o
[ 50%] Built target motion_planning_api_tutorial
Scanning dependencies of target subframes_tutorial
[ 52%] Building CXX object moveit_tutorials/doc/subframes/CMakeFiles/subframes_tutorial.dir/src/subframes_tutorial.cpp.o
[ 54%] Linking CXX executable "/home/adminspin*/catkin_ws/devel/lib/moveit_tutorials/planning_scene_tutorial"
[ 54%] Built target pick_place_tutorial
Scanning dependencies of target trajopt_example
[ 56%] Building CXX object moveit_tutorials/doc/trajopt_planner/CMakeFiles/trajopt_example.dir/src/trajopt_example.cpp.o
[ 59%] Linking CXX executable "/home/adminspin*/catkin_ws/devel/lib/moveit_tutorials/detect_and_add_cylinder_collision_object_demo"
[ 61%] Linking CXX shared library "/home/adminspin*/catkin_ws/devel/lib/libinteractivity_utils.so"
[ 61%] Built target planning_scene_tutorial
Scanning dependencies of target lerp_example
[ 63%] Building CXX object moveit_tutorials/doc/creating_moveit_plugins/lerp_motion_planner/CMakeFiles/lerp_example.dir/src/lerp_example.cpp.o
[ 63%] Built target interactivity_utils
Scanning dependencies of target moveit_lerp_planner_plugin
[ 65%] Building CXX object moveit_tutorials/doc/creating_moveit_plugins/lerp_motion_planner/CMakeFiles/moveit_lerp_planner_plugin.dir/src/lerp_planner_manager.cpp.o
[ 68%] Linking CXX executable "/home/adminspin*/catkin_ws/devel/lib/moveit_tutorials/robot_model_and_robot_state_tutorial"
CMakeFiles/detect_and_add_cylinder_collision_object_demo.dir/src/detect_and_add_cylinder_collision_object_demo.cpp.o: In function `boost::system::generic_category()':
detect_and_add_cylinder_collision_object_demo.cpp:(.text._ZN5boost6system16generic_categoryEv[_ZN5boost6system16generic_categoryEv]+0x6): undefined reference to `boost::system::detail::generic_category_instance'
[ 70%] Linking CXX executable "/home/adminspin*/catkin_ws/devel/lib/moveit_tutorials/state_display_tutorial"
clang: error: linker command failed with exit code 1 (use -v to see invocation)
moveit_tutorials/doc/perception_pipeline/CMakeFiles/detect_and_add_cylinder_collision_object_demo.dir/build.make:385: recipe for target '/home/adminspin*/catkin_ws/devel/lib/moveit_tutorials/detect_and_add_cylinder_collision_object_demo' failed
make[2]: *** [/home/adminspin*/catkin_ws/devel/lib/moveit_tutorials/detect_and_add_cylinder_collision_object_demo] Error 1
CMakeFiles/Makefile2:4747: recipe for target 'moveit_tutorials/doc/perception_pipeline/CMakeFiles/detect_and_add_cylinder_collision_object_demo.dir/all' failed
make[1]: *** [moveit_tutorials/doc/perception_pipeline/CMakeFiles/detect_and_add_cylinder_collision_object_demo.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 72%] Building CXX object moveit_tutorials/doc/creating_moveit_plugins/lerp_motion_planner/CMakeFiles/moveit_lerp_planner_plugin.dir/src/lerp_interface.cpp.o
[ 75%] Linking CXX executable "/home/adminspin*/catkin_ws/devel/lib/moveit_tutorials/planning_scene_ros_api_tutorial"
/home/adminspin*/catkin_ws/src/moveit_tutorials/doc/subframes/src/subframes_tutorial.cpp:105:7: error: no member named 'pose' in 'moveit_msgs::CollisionObject_<std::allocator<void> >'
  box.pose.position.z = z_offset_box;
  ~~~ ^
/home/adminspin*/catkin_ws/src/moveit_tutorials/doc/subframes/src/subframes_tutorial.cpp:106:7: error: no member named 'pose' in 'moveit_msgs::CollisionObject_<std::allocator<void> >'
  box.pose.orientation.w = 1.0;  // Neutral orientation
  ~~~ ^
/home/adminspin*/catkin_ws/src/moveit_tutorials/doc/subframes/src/subframes_tutorial.cpp:121:7: error: no member named 'subframe_names' in 'moveit_msgs::CollisionObject_<std::allocator<void> >'
  box.subframe_names.resize(3);
  ~~~ ^
/home/adminspin*/catkin_ws/src/moveit_tutorials/doc/subframes/src/subframes_tutorial.cpp:122:7: error: no member named 'subframe_poses' in 'moveit_msgs::CollisionObject_<std::allocator<void> >'
  box.subframe_poses.resize(3);
  ~~~ ^
/home/adminspin*/catkin_ws/src/moveit_tutorials/doc/subframes/src/subframes_tutorial.cpp:124:7: error: no member named 'subframe_names' in 'moveit_msgs::CollisionObject_<std::allocator<void> >'
  box.subframe_names[0] = "bottom";
  ~~~ ^
/home/adminspin*/catkin_ws/src/moveit_tutorials/doc/subframes/src/subframes_tutorial.cpp:125:7: error: no member named 'subframe_poses' in 'moveit_msgs::CollisionObject_<std::allocator<void> >'
  box.subframe_poses[0].position.y = -.05;
  ~~~ ^
/home/adminspin*/catkin_ws/src/moveit_tutorials/doc/subframes/src/subframes_tutorial.cpp:129:7: error: no member named 'subframe_poses' in 'moveit_msgs::CollisionObject_<std::allocator<void> >'
  box.subframe_poses[0].orientation = tf2::toMsg(orientation);
  ~~~ ^
/home/adminspin*/catkin_ws/src/moveit_tutorials/doc/subframes/src/subframes_tutorial.cpp:132:7: error: no member named 'subframe_names' in 'moveit_msgs::CollisionObject_<std::allocator<void> >'
  box.subframe_names[1] = "top";
  ~~~ ^
/home/adminspin*/catkin_ws/src/moveit_tutorials/doc/subframes/src/subframes_tutorial.cpp:133:7: error: no member named 'subframe_poses' in 'moveit_msgs::CollisionObject_<std::allocator<void> >'
  box.subframe_poses[1].position.y = .05;
  ~~~ ^
/home/adminspin*/catkin_ws/src/moveit_tutorials/doc/subframes/src/subframes_tutorial.cpp:135:7: error: no member named 'subframe_poses' in 'moveit_msgs::CollisionObject_<std::allocator<void> >'
  box.subframe_poses[1].orientation = tf2::toMsg(orientation);
  ~~~ ^
/home/adminspin*/catkin_ws/src/moveit_tutorials/doc/subframes/src/subframes_tutorial.cpp:137:7: error: no member named 'subframe_names' in 'moveit_msgs::CollisionObject_<std::allocator<void> >'
  box.subframe_names[2] = "corner";
  ~~~ ^
/home/adminspin*/catkin_ws/src/moveit_tutorials/doc/subframes/src/subframes_tutorial.cpp:138:7: error: no member named 'subframe_poses' in 'moveit_msgs::CollisionObject_<std::allocator<void> >'
  box.subframe_poses[2].position.x = .025;
  ~~~ ^
/home/adminspin*/catkin_ws/src/moveit_tutorials/doc/subframes/src/subframes_tutorial.cpp:139:7: error: no member named 'subframe_poses' in 'moveit_msgs::CollisionObject_<std::allocator<void> >'
  box.subframe_poses[2].position.y = -.05;
  ~~~ ^
/home/adminspin*/catkin_ws/src/moveit_tutorials/doc/subframes/src/subframes_tutorial.cpp:140:7: error: no member named 'subframe_poses' in 'moveit_msgs::CollisionObject_<std::allocator<void> >'
  box.subframe_poses[2].position.z = -.01;
  ~~~ ^
/home/adminspin*/catkin_ws/src/moveit_tutorials/doc/subframes/src/subframes_tutorial.cpp:142:7: error: no member named 'subframe_poses' in 'moveit_msgs::CollisionObject_<std::allocator<void> >'
  box.subframe_poses[2].orientation = tf2::toMsg(orientation);
  ~~~ ^
/home/adminspin*/catkin_ws/src/moveit_tutorials/doc/subframes/src/subframes_tutorial.cpp:148:12: error: no member named 'pose' in 'moveit_msgs::CollisionObject_<std::allocator<void> >'
  cylinder.pose.position.z = z_offset_cylinder;
  ~~~~~~~~ ^
/home/adminspin*/catkin_ws/src/moveit_tutorials/doc/subframes/src/subframes_tutorial.cpp:150:12: error: no member named 'pose' in 'moveit_msgs::CollisionObject_<std::allocator<void> >'
  cylinder.pose.orientation = tf2::toMsg(orientation);
  ~~~~~~~~ ^
/home/adminspin*/catkin_ws/src/moveit_tutorials/doc/subframes/src/subframes_tutorial.cpp:158:12: error: no member named 'subframe_poses' in 'moveit_msgs::CollisionObject_<std::allocator<void> >'
  cylinder.subframe_poses.resize(1);
  ~~~~~~~~ ^
/home/adminspin*/catkin_ws/src/moveit_tutorials/doc/subframes/src/subframes_tutorial.cpp:159:12: error: no member named 'subframe_names' in 'moveit_msgs::CollisionObject_<std::allocator<void> >'
  cylinder.subframe_names.resize(1);
  ~~~~~~~~ ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
moveit_tutorials/doc/subframes/CMakeFiles/subframes_tutorial.dir/build.make:62: recipe for target 'moveit_tutorials/doc/subframes/CMakeFiles/subframes_tutorial.dir/src/subframes_tutorial.cpp.o' failed
make[2]: *** [moveit_tutorials/doc/subframes/CMakeFiles/subframes_tutorial.dir/src/subframes_tutorial.cpp.o] Error 1
CMakeFiles/Makefile2:5132: recipe for target 'moveit_tutorials/doc/subframes/CMakeFiles/subframes_tutorial.dir/all' failed
make[1]: *** [moveit_tutorials/doc/subframes/CMakeFiles/subframes_tutorial.dir/all] Error 2
[ 77%] Building CXX object moveit_tutorials/doc/creating_moveit_plugins/lerp_motion_planner/CMakeFiles/moveit_lerp_planner_plugin.dir/src/lerp_planning_context.cpp.o
[ 77%] Built target robot_model_and_robot_state_tutorial
/home/adminspin*/catkin_ws/src/moveit_tutorials/doc/trajopt_planner/src/trajopt_example.cpp:186:7: error: no member named 'reference_trajectories' in 'moveit_msgs::MotionPlanRequest_<std::allocator<void> >'
  req.reference_trajectories.resize(1);
  ~~~ ^
/home/adminspin*/catkin_ws/src/moveit_tutorials/doc/trajopt_planner/src/trajopt_example.cpp:187:7: error: no member named 'reference_trajectories' in 'moveit_msgs::MotionPlanRequest_<std::allocator<void> >'
  req.reference_trajectories[0].joint_trajectory.resize(1);
  ~~~ ^
/home/adminspin*/catkin_ws/src/moveit_tutorials/doc/trajopt_planner/src/trajopt_example.cpp:189:7: error: no member named 'reference_trajectories' in 'moveit_msgs::MotionPlanRequest_<std::allocator<void> >'
  req.reference_trajectories[0].joint_trajectory[0].points.resize(N_STEPS + 1);
  ~~~ ^
/home/adminspin*/catkin_ws/src/moveit_tutorials/doc/trajopt_planner/src/trajopt_example.cpp:190:7: error: no member named 'reference_trajectories' in 'moveit_msgs::MotionPlanRequest_<std::allocator<void> >'
  req.reference_trajectories[0].joint_trajectory[0].joint_names = joint_names;
  ~~~ ^
/home/adminspin*/catkin_ws/src/moveit_tutorials/doc/trajopt_planner/src/trajopt_example.cpp:191:7: error: no member named 'reference_trajectories' in 'moveit_msgs::MotionPlanRequest_<std::allocator<void> >'
  req.reference_trajectories[0].joint_trajectory[0].points[0].positions = current_joint_values;
  ~~~ ^
/home/adminspin*/catkin_ws/src/moveit_tutorials/doc/trajopt_planner/src/trajopt_example.cpp:203:9: error: no member named 'reference_trajectories' in 'moveit_msgs::MotionPlanRequest_<std::allocator<void> >'
    req.reference_trajectories[0].joint_trajectory[0].joint_names = joint_names;
    ~~~ ^
/home/adminspin*/catkin_ws/src/moveit_tutorials/doc/trajopt_planner/src/trajopt_example.cpp:204:9: error: no member named 'reference_trajectories' in 'moveit_msgs::MotionPlanRequest_<std::allocator<void> >'
    req.reference_trajectories[0].joint_trajectory[0].points[step_index].positions = joint_values;
    ~~~ ^
[ 77%] Built target state_display_tutorial
[ 77%] Built target planning_scene_ros_api_tutorial
7 errors generated.
moveit_tutorials/doc/trajopt_planner/CMakeFiles/trajopt_example.dir/build.make:62: recipe for target 'moveit_tutorials/doc/trajopt_planner/CMakeFiles/trajopt_example.dir/src/trajopt_example.cpp.o' failed
make[2]: *** [moveit_tutorials/doc/trajopt_planner/CMakeFiles/trajopt_example.dir/src/trajopt_example.cpp.o] Error 1
CMakeFiles/Makefile2:5470: recipe for target 'moveit_tutorials/doc/trajopt_planner/CMakeFiles/trajopt_example.dir/all' failed
make[1]: *** [moveit_tutorials/doc/trajopt_planner/CMakeFiles/trajopt_example.dir/all] Error 2
[ 79%] Linking CXX shared library "/home/adminspin*/catkin_ws/devel/lib/libmoveit_lerp_planner_plugin.so"
[ 81%] Linking CXX executable "/home/adminspin*/catkin_ws/devel/lib/moveit_tutorials/lerp_example"
[ 81%] Built target moveit_lerp_planner_plugin
[ 81%] Built target lerp_example
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

**Comment by rhaschke** [comment]
When you are working on Melodic, you should use the Melodic branch of the tutorials as stated [here](http://docs.ros.org/en/melodic/api/moveit_tutorials/html/doc/getting_started/getting_started.html#download-example-code).
