### ISSUE TITLE
potential error in documentation

### ISSUE THREAD

**Issue by RumailM** [ros-planning/moveit_tutorials#731]
If I understand correctly the master branch of this repo is meant for ros noetic. I was going through the tutorials and I noticed that for the panda_moveit_config we are chosing the melodic-devel branch instead of the noetic-devel branch. Is there a reason for this?

https://github.com/ros-planning/moveit_tutorials/blob/master/doc/getting_started/getting_started.rst line 46

`git clone https://github.com/ros-planning/panda_moveit_config.git -b melodic-devel`

**Comment by rhaschke** [comment]
Closed via #732
