### ISSUE TITLE
Regd. Setup Assistant Tutorial

### ISSUE THREAD

**Issue by karnikram** [ros-planning/moveit_tutorials#734]
### Description

Hi, I'm trying to setup the Franka Panda arm for Gazebo by following the setup assistant [tutorial](https://ros-planning.github.io/moveit_tutorials/doc/setup_assistant/setup_assistant_tutorial.html). But the tutorial refers to the file `panda_arm.urdf.xacro` which is not available in the Franka [package](https://github.com/frankaemika/franka_ros/tree/noetic-devel/franka_description/robots/panda). There is only a `panda.urdf.xacro` file but that comes without the gripper so I am unable to follow the subsequent steps. 

Is there a way to resolve this? Thanks!

### Your environment
* ROS Distro: Noetic
* OS Version: Ubuntu 20.04
* Source build from master

**Comment by rhaschke** [comment]
If you have a look into the way [panda_moveit_config loads the URDF](https://github.com/ros-planning/panda_moveit_config/blob/noetic-devel/launch/planning_context.launch#L11), you see that there is an argument `hand`, which can be set to true to enable the hand:
```
xacro '$(find franka_description)/robots/panda/panda.urdf.xacro' hand:=$(arg load_gripper) arm_id:=$(arg arm_id)"
```
Unfortunately, @frankaemika maintainers have hidden all argument declarations in file [`franka_robot.xacro`](https://github.com/frankaemika/franka_ros/blob/noetic-devel/franka_description/robots/common/franka_robot.xacro#L4-L12) with their latest refactoring.
