### ISSUE TITLE
Trajopt installation

### ISSUE THREAD

**Issue by STAY-Melody** [ros-planning/moveit_tutorials#784]
### Description

Hi!

When I was following the tutorial on `trajopt`, I was confused whether `trajopt` needed to be installed separately rather than via ros install?

If the former is the case, then it seems that `trajopt` has a lot of problems with the installation on Ubuntu 20.04, one of which is the `openrave` installation.

Is there any recommended way to install `trajopt` without spending time on the `openrave` installation, which is somewhat outdated in comparison to Ubuntu 20.04 and has problems with some dependencies.

Thanks!

### Your environment
* ROS Distro: Noetic
* OS Version: Ubuntu 20.04

**Comment by simonschmeisser** [comment]
The trajopt planner in MoveIt is currently disabled so you need to enable it and build from source. In it's current state it does not include collision checking. There is an open merge request to improve things slightly.
