### ISSUE TITLE
Errors in the tutorial "Move Group C++ Interface"

### ISSUE THREAD

**Issue by struggler-lu** [ros-planning/moveit_tutorials#785]
### Description

I follow the tutorial to operate and I met the errors when I tried to attach objects to the robot and plan the path.The start state was in collision so the path planning was failed.The errors encountered are shown in the following figures.
![image](https://github.com/ros-planning/moveit_tutorials/assets/129816388/f6458497-6ddf-4792-965d-4e3bce81244f)
**Figure1**
![image](https://github.com/ros-planning/moveit_tutorials/assets/129816388/41e5638d-c285-4dab-87ad-a13488671028)
**Figure2**

It seems that there is a collision between the object attached to the robot and the grippers.

![image](https://github.com/ros-planning/moveit_tutorials/assets/129816388/6d0c8548-1804-476b-bcc3-3cc0b55329f3)
### Your environment
* ROS Distro: Noetic
* OS Version: Ubuntu 20.04

### Steps to reproduce
I followed this tutorial:
https://ros-planning.github.io/moveit_tutorials/doc/move_group_interface/move_group_interface_tutorial.html#

### Expected behaviour
The result may look something like the GIFs in the tutorial.

**Comment by rhaschke** [comment]
Thanks for reporting. The solution is to [declare `touch_links`](https://github.com/ros-planning/moveit_tutorials/pull/790/files#diff-a5c0141aeeaa8ad7836f3b230e2e8cfa49fd26ea3dcfe3496b83478f58d7a265R434), i.e. links which are allowed to touch the object.
