### ISSUE TITLE
No such file or directory: /opt/ros/melodic/share/franka_description/robots/panda/panda.urdf.xacro [Errno 2] No such file or directory: '/opt/ros/melodic/share/franka_description/robots/panda/panda.urdf.xacro'

### ISSUE THREAD

**Issue by lostgab** [ros-planning/moveit_tutorials#794]
Finished getting started on ROS at http://docs.ros.org/en/melodic/api/moveit_tutorials/html/doc/getting_started/getting_started.html
then tried to do move it
![image](https://github.com/ros-planning/moveit_tutorials/assets/21375609/c04ee940-d2ed-4d8d-b015-30d6cd2a95c5)
but got this error instead, anybody can help? The tutorial on ROS is not very good for begineers
![image](https://github.com/ros-planning/moveit_tutorials/assets/21375609/aed104ef-f2dc-4659-b3a0-6c7ecb593395)

Overview of your issue here.

### Your environment
* ROS Distro: [Indigo|Jade|Kinetic]
* OS Version: e.g. Ubuntu 16.04
* Source or Binary build?
* If binary, which release version?
* If source, which git commit or tag?

### Steps to reproduce
Tell us how to reproduce this issue. Attempt to provide a working demo, perhaps using Docker.

### Expected behaviour
Tell us what should happen

### Backtrace or Console output

Use [gist.github.com](gist.github.com) to copy-paste the console output or segfault backtrace using gdb.

**Comment by rhaschke** [comment]
Looks like you missed to install package dependencies as stated in the _Getting Started_ tutorial:
```sh
cd ~/ws_moveit/src
rosdep install -y --from-paths . --ignore-src --rosdistro melodic
```

Particularly, you are missing franka_description:
`sudo apt install ros-melodic-franka-description`
