### ISSUE TITLE
IKFast Tutorial not clear

### ISSUE THREAD

**Issue by zacharyyamaoka** [ros-planning/moveit_tutorials#797]
Hi,

I was going through the IK fast tutorial (https://ros-planning.github.io/moveit_tutorials/doc/ikfast/ikfast_tutorial.html
) and it was not clear to me that I could run these commands

"sudo apt-get install ros-${ROS_DISTRO}-moveit-kinematics"

from the host computer and not from within the docker container. It was only until I tried to run: 

rosrun moveit_kinematics auto_create_ikfast_moveit_plugin.sh --iktype Transform6D /tmp/$MYROBOT_NAME.urdf <planning_group_name> <base_link> <eef_link>

that I realised that auto_create_ikfast_moveit_plugin.sh did not exist.

If something could be stated saying something to the effect of  "ALL COMMANDS SHOULD BE RUN ON HOST COMPUTER" would help noobs like my self,

Thanks for your consideration,

Zach

**Comment by rhaschke** [comment]
Thanks for the feedback. But I think the tutorial is rather clear: If you just follow the given instructions it should work.
There is no instruction to pull or run the linked docker image. This was only mentioned for completeness.
