### ISSUE TITLE
Keys expired in IKFast installation script.

### ISSUE THREAD

**Issue by c-oechsner** [ros-planning/moveit_tutorials#813]
### Description
Running the `auto_create_ikfast_moveit_plugin.sh` script fails due to expired keys.

### Your environment
* ROS Distro: Noetic
* OS Version: Ubuntu 20.04
* Binary build: 1.16.0

### Steps to reproduce
Follow the tutorial at https://ros-planning.github.io/moveit_tutorials/doc/ikfast/ikfast_tutorial.html

### Expected behaviour
The script should run without errors.

### Backtrace or Console output
[ikfast.log](https://github.com/ros-planning/moveit_tutorials/files/14332344/ikfast.log)

Is there an easy fix for this? For example use `--allow-unauthenticated upgrade` ?

Update: adding the flag worked and the script went through. Will report on the outcome soon.

**Comment by rhaschke** [comment]
I cannot reproduce this issue. We regularly run the ikfast scripts as part of our CI and this works as expected:
https://github.com/ros-planning/moveit/actions/runs/7977588247/job/21780798341

Maybe the key server was temporarily out-of-order?
