### ISSUE TITLE
Slight tweak to ros_visualization tutorial (Scene Robot -> Show Robot Visual)

### ISSUE THREAD

**Issue by jwhendy** [ros-planning/moveit_tutorials#89]
Hello,

Just going through the [tutorials]() and saw this bit:

>The display states for each of these visualizations can be toggled on and off using checkboxes.
>
>1. The start state using the "Query Start State" checkbox in the "Planning Request" tab.
>2. The goal state using the "Query Goal State" checkbox in the "Planning Request" tab.
>3. The planning scene robot using the "Show Scene Robot" checkbox in the "Scene Robot" tab.
>4. The planned path using the "Show Robot Visual" checkbox in the "Planned Path" tab.

If I'm correct that the third should be `Show Robot Visual`, I can submit a PR.

What I see in RViz:

![scene_robot](https://user-images.githubusercontent.com/379357/28791488-41ed8414-75f2-11e7-881e-0c9ddecc6c37.png)

**Comment by v4hn** [comment]
Of course you are right. Could you file a pull-request that fixes it?

**Comment by jwhendy** [comment]
Had it waiting :) Submitted. Let me know if you need any adjustments to it. Thanks!
